# -*- coding: utf-8 -*-
"""DS_EVA02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liNrXKxPvavMjg9_hvJ0hg_5qbiF3zEk
"""

# 1. 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 2. 데이터셋 압축 풀기 (경로가 다르다면 수정해 줘)
!unzip -q /content/drive/MyDrive/dataset.zip -d /content/

# 3. timm 라이브러리 설치
!pip install timm

"""
ACFM v2 - Part 1
Animal Crossing Face Matcher
---------------------------------
Part 1 contains:
- Imports
- Config
- Utility functions
- Logger
- Dataset builder
- Model builder

Part 2 will add:
- train_model()
"""

import os
import csv
import random
import numpy as np
import torch
import torch.nn as nn
import timm

from dataclasses import dataclass
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
from sklearn.model_selection import StratifiedShuffleSplit


# ==========================================================
# Config
# ==========================================================

@dataclass
class Config:

    # Dataset
    DATA_DIR = "/content/drive/MyDrive/content/dataset"

    # Output
    RESULT_DIR = "/content/drive/MyDrive/results"
    MODEL_DIR = os.path.join(RESULT_DIR, "models")
    LOG_DIR = os.path.join(RESULT_DIR, "logs")
    GRAPH_DIR = os.path.join(RESULT_DIR, "graphs")
    EVAL_DIR = os.path.join(RESULT_DIR, "evaluation")

    # Image
    IMAGE_SIZE = 224

    # Training
    BATCH_SIZE = 32
    NUM_WORKERS = 2
    RANDOM_SEED = 42

    STEP1_EPOCHS = 10
    STEP2_EPOCHS = 30

    STEP1_LR = 1e-3
    STEP2_LR = 5e-5

    WEIGHT_DECAY = 0.05
    PATIENCE = 5

    LABEL_SMOOTHING = 0.1

    MODEL_NAME = "eva02_base_patch14_224.mim_in22k"


CFG = Config()


# ==========================================================
# Utils
# ==========================================================

def create_directories():
    for d in [
        CFG.RESULT_DIR,
        CFG.MODEL_DIR,
        CFG.LOG_DIR,
        CFG.GRAPH_DIR,
        CFG.EVAL_DIR,
    ]:
        os.makedirs(d, exist_ok=True)


def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def get_device():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device : {device}")
    return device


# ==========================================================
# Logger
# ==========================================================

class CSVLogger:
    def __init__(self, filename, header):
        self.filename = filename

        with open(filename, "w", newline="", encoding="utf-8-sig") as f:
            writer = csv.writer(f)
            writer.writerow(header)
    def write(self, row):
        with open(self.filename, "a", newline="", encoding="utf-8-sig") as f:
            writer = csv.writer(f)
            writer.writerow(row)


# ==========================================================
# Transform
# ==========================================================

MEAN = [0.48145466, 0.4578275, 0.40821073]
STD = [0.26862954, 0.26130258, 0.27577711]

train_transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomResizedCrop(CFG.IMAGE_SIZE, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(0.5),
    transforms.RandomRotation(10),
    transforms.ColorJitter(
        brightness=0.15,
        contrast=0.15,
        saturation=0.10
    ),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
    transforms.RandomErasing(
        p=0.25,
        scale=(0.02, 0.15)
    )
])

val_transform = transforms.Compose([
    transforms.Resize((CFG.IMAGE_SIZE, CFG.IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD)
])


# ==========================================================
# Dataset
# ==========================================================

def build_dataset():

    train_full = datasets.ImageFolder(
        CFG.DATA_DIR,
        transform=train_transform
    )

    val_full = datasets.ImageFolder(
        CFG.DATA_DIR,
        transform=val_transform
    )

    labels = [x[1] for x in train_full.samples]

    splitter = StratifiedShuffleSplit(
        n_splits=1,
        test_size=0.2,
        random_state=CFG.RANDOM_SEED
    )

    train_idx, val_idx = next(
        splitter.split(np.zeros(len(labels)), labels)
    )

    train_dataset = Subset(train_full, train_idx)
    val_dataset = Subset(val_full, val_idx)

    train_loader = DataLoader(
        train_dataset,
        batch_size=CFG.BATCH_SIZE,
        shuffle=True,
        num_workers=CFG.NUM_WORKERS,
        pin_memory=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=CFG.BATCH_SIZE,
        shuffle=False,
        num_workers=CFG.NUM_WORKERS,
        pin_memory=True
    )

    class_names = train_full.classes

    with open(os.path.join(CFG.RESULT_DIR, "classes.txt"),
              "w", encoding="utf-8") as f:
        for idx, name in enumerate(class_names):
            f.write(f"{idx}\t{name}\n")

    print(f"Train : {len(train_dataset)}")
    print(f"Validation : {len(val_dataset)}")
    print(f"Classes : {len(class_names)}")

    return train_loader, val_loader, class_names


# ==========================================================
# Model
# ==========================================================

def build_model(num_classes, device):

    model = timm.create_model(
        CFG.MODEL_NAME,
        pretrained=True
    )

    print(type(model))
    print(hasattr(model, "blocks"))
    print(len(model.blocks))

    for p in model.parameters():
        p.requires_grad = False

    model.head = nn.Sequential(
        nn.Linear(model.num_features, 512),
        nn.LayerNorm(512),
        nn.GELU(),
        nn.Dropout(0.3),

        nn.Linear(512, 256),
        nn.LayerNorm(256),
        nn.GELU(),
        nn.Dropout(0.2),

        nn.Linear(256, num_classes)
    )


    return model.to(device)


# ==========================================================
# Bootstrap
# ==========================================================

if __name__ == "__main__":

    create_directories()
    seed_everything(CFG.RANDOM_SEED)

    device = get_device()

    train_loader, val_loader, classes = build_dataset()

    model = build_model(
        len(classes),
        device
    )

    print(model.head)
    print("\\nPart 1 completed successfully.")

"""
ACFM v2 - Part 2
Append this file below Part1 contents or merge into eva02_project.py.

Contains:
- EarlyStopping
- train_one_epoch
- validate_one_epoch
- train_model
"""

import os
import time
import torch
import torch.nn as nn
import torch.optim as optim

# ==========================================================
# EarlyStopping
# ==========================================================

class EarlyStopping:

    def __init__(self, patience=5):
        self.patience = patience
        self.best_acc = 0.0
        self.counter = 0

    def step(self, val_acc):
        if val_acc > self.best_acc:
            self.best_acc = val_acc
            self.counter = 0
            return False, True

        self.counter += 1
        return self.counter >= self.patience, False


# ==========================================================
# Train / Validation
# ==========================================================

def train_one_epoch(model, loader, criterion, optimizer, device):

    model.train()

    total_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        total_loss += loss.item() * images.size(0)

        pred = outputs.argmax(1)

        correct += (pred == labels).sum().item()

        total += labels.size(0)

    return total_loss / total, 100 * correct / total


@torch.no_grad()
def validate_one_epoch(model, loader, criterion, device):

    model.eval()

    total_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        outputs = model(images)

        loss = criterion(outputs, labels)

        total_loss += loss.item() * images.size(0)

        pred = outputs.argmax(1)

        correct += (pred == labels).sum().item()

        total += labels.size(0)

    return total_loss / total, 100 * correct / total


# ==========================================================
# Main Train Function
# ==========================================================

def train_model(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        device,
        epochs,
        save_name,
        log_name):

    criterion = nn.CrossEntropyLoss(
        label_smoothing=CFG.LABEL_SMOOTHING
    )

    logger = CSVLogger(
        os.path.join(CFG.LOG_DIR, log_name),
        [
            "Epoch",
            "Train Loss",
            "Train Acc",
            "Val Loss",
            "Val Acc",
            "LR"
        ]
    )

    stopper = EarlyStopping(CFG.PATIENCE)

    best_acc = 0.0

    for epoch in range(epochs):

        start = time.time()

        train_loss, train_acc = train_one_epoch(
            model,
            train_loader,
            criterion,
            optimizer,
            device
        )

        val_loss, val_acc = validate_one_epoch(
            model,
            val_loader,
            criterion,
            device
        )

        scheduler.step()

        lr = optimizer.param_groups[0]["lr"]

        logger.write([
            epoch + 1,
            round(train_loss, 5),
            round(train_acc, 2),
            round(val_loss, 5),
            round(val_acc, 2),
            lr
        ])

        print(
            f"Epoch [{epoch+1}/{epochs}] "
            f"| Train {train_loss:.4f}/{train_acc:.2f}% "
            f"| Val {val_loss:.4f}/{val_acc:.2f}% "
            f"| LR {lr:.2e} "
            f"| {time.time()-start:.0f}s"
        )

        stop, improved = stopper.step(val_acc)

        if improved:
            torch.save(
                model.state_dict(),
                os.path.join(CFG.MODEL_DIR, save_name)
            )

            best_acc = val_acc

            print("✓ Best Model Saved")

        if stop:
            print("Early Stopping")
            break

    print(f"\nBest Validation Accuracy : {best_acc:.2f}%")

    return model


# ==========================================================
# STEP1
# ==========================================================

def run_step1(model, train_loader, val_loader, device):

    print("\n===== STEP1 =====")

    for p in model.parameters():
        p.requires_grad = False

    for p in model.head.parameters():
        p.requires_grad = True

    optimizer = optim.AdamW(
        model.head.parameters(),
        lr=CFG.STEP1_LR,
        weight_decay=CFG.WEIGHT_DECAY
    )

    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=CFG.STEP1_EPOCHS
    )

    train_model(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        device,
        CFG.STEP1_EPOCHS,
        "step1_best.pth",
        "step1_log.csv"
    )


# ==========================================================
# STEP2
# ==========================================================

def run_step2(model, train_loader, val_loader, device):

    print("\n===== STEP2 =====")

  # ---------------------------------------
  # 1. 모든 파라미터 동결
  # ---------------------------------------
    for p in model.parameters():
        p.requires_grad = False

  # ---------------------------------------
  # 2. Head는 학습
  # ---------------------------------------

    for p in model.head.parameters():
        p.requires_grad = True

  # ---------------------------------------
  # 3. 마지막에 Transformer Block만 학습
  # ---------------------------------------
    for p in model.blocks[-1].parameters():
        p.requires_grad = True

    optimizer = optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=CFG.STEP2_LR,
        weight_decay=CFG.WEIGHT_DECAY
    )

    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=CFG.STEP2_EPOCHS
    )

    train_model(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        device,
        CFG.STEP2_EPOCHS,
        "best_model.pth",
        "step2_log.csv"
    )

print("Part2 Ready")

"""
ACFM v2 - Part 3
Evaluation Module

Requires:
- CFG
- build_dataset()
- build_model()
- train_model()

Adds:
- evaluate_model()
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    precision_recall_fscore_support
)

import torch


@torch.no_grad()
def evaluate_model(model, loader, class_names, device, weight_name="best_model.pth"):

    print("\n==========================")
    print("Evaluation")
    print("==========================")

    weight_path = os.path.join(CFG.MODEL_DIR, weight_name)

    if os.path.exists(weight_path):
        model.load_state_dict(torch.load(weight_path, map_location=device))
        print(f"Loaded : {weight_name}")
    else:
        print("Best model not found. Evaluating current model.")

    model.eval()

    y_true = []
    y_pred = []

    for images, labels in loader:

        images = images.to(device)
        outputs = model(images)

        preds = outputs.argmax(1).cpu().numpy()

        y_pred.extend(preds.tolist())
        y_true.extend(labels.numpy().tolist())

    labels_idx = list(range(len(class_names)))

    cm = confusion_matrix(
        y_true,
        y_pred,
        labels=labels_idx
    )

    # ----------------------------------------------------
    # Character Accuracy
    # ----------------------------------------------------

    class_acc = []

    for i in range(len(class_names)):
        total = cm[i].sum()

        acc = 0 if total == 0 else cm[i, i] / total

        class_acc.append(acc)

    acc_df = pd.DataFrame({
        "Character": class_names,
        "Accuracy": np.round(np.array(class_acc) * 100, 2)
    })

    acc_df.to_csv(
        os.path.join(CFG.EVAL_DIR, "class_accuracy.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    print("\nCharacter Accuracy")
    print(acc_df)

    # ----------------------------------------------------
    # Precision / Recall / F1
    # ----------------------------------------------------

    precision, recall, f1, support = precision_recall_fscore_support(
        y_true,
        y_pred,
        labels=labels_idx,
        zero_division=0
    )

    metric_df = pd.DataFrame({
        "Character": class_names,
        "Support": support,
        "Precision": np.round(precision, 4),
        "Recall": np.round(recall, 4),
        "F1": np.round(f1, 4)
    })

    metric_df.to_csv(
        os.path.join(CFG.EVAL_DIR, "class_metrics.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    # ----------------------------------------------------
    # Classification Report
    # ----------------------------------------------------

    report = classification_report(
        y_true,
        y_pred,
        target_names=class_names,
        labels=labels_idx,
        output_dict=True,
        zero_division=0
    )

    report_df = pd.DataFrame(report).transpose()

    report_df.to_csv(
        os.path.join(CFG.EVAL_DIR, "classification_report.csv"),
        encoding="utf-8-sig"
    )

    # ----------------------------------------------------
    # Confusion Matrix CSV
    # ----------------------------------------------------

    cm_df = pd.DataFrame(
        cm,
        index=class_names,
        columns=class_names
    )

    cm_df.to_csv(
        os.path.join(CFG.EVAL_DIR, "confusion_matrix.csv"),
        encoding="utf-8-sig"
    )

    # ----------------------------------------------------
    # Confusion Matrix PNG
    # ----------------------------------------------------

    fig_size = max(8, len(class_names))

    plt.figure(figsize=(fig_size, fig_size))
    plt.imshow(cm, cmap="Blues")
    plt.title("Confusion Matrix")
    plt.colorbar()

    plt.xticks(range(len(class_names)), class_names, rotation=90)
    plt.yticks(range(len(class_names)), class_names)

    plt.xlabel("Predicted")
    plt.ylabel("True")

    for i in range(len(class_names)):
        for j in range(len(class_names)):
            plt.text(
                j,
                i,
                str(cm[i, j]),
                ha="center",
                va="center",
                fontsize=8
            )

    plt.tight_layout()

    plt.savefig(
        os.path.join(CFG.EVAL_DIR, "confusion_matrix.png"),
        dpi=300
    )

    plt.close()

    # ----------------------------------------------------
    # Most Confused Character
    # ----------------------------------------------------

    confused = []

    print("\nMost Confused Character")

    for i in range(len(class_names)):

        row = cm[i].copy()
        row[i] = 0

        if row.sum() == 0:
            target = "-"
            count = 0
        else:
            idx = int(np.argmax(row))
            target = class_names[idx]
            count = int(row[idx])

        confused.append({
            "Character": class_names[i],
            "Most Confused": target,
            "Count": count
        })

        print(f"{class_names[i]} -> {target} ({count})")

    confused_df = pd.DataFrame(confused)

    confused_df.to_csv(
        os.path.join(CFG.EVAL_DIR, "confused_character.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    overall = (np.array(y_true) == np.array(y_pred)).mean() * 100

    print("\n===================================")
    print(f"Overall Accuracy : {overall:.2f}%")
    print("Evaluation Complete")
    print("===================================")

"""
ACFM v2 - Part 4
Prediction + Main

Append below Part1~3 or merge into eva02_project.py
"""

import os
import torch
from PIL import Image


def predict_image(image_path, model, class_names, device,
                  weight_name="best_model.pth"):

    weight_path = os.path.join(CFG.MODEL_DIR, weight_name)
    if os.path.exists(weight_path):
        model.load_state_dict(torch.load(weight_path, map_location=device))

    model.eval()

    image = Image.open(image_path).convert("RGB")
    tensor = val_transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(tensor)
        probs = torch.softmax(logits, dim=1)

    conf, pred = torch.max(probs, dim=1)

    print("=" * 40)
    print("Prediction")
    print("=" * 40)
    print(f"Character : {class_names[pred.item()]}")
    print(f"Confidence: {conf.item()*100:.2f}%")
    print("=" * 40)

    return class_names[pred.item()], conf.item()


def main():

    create_directories()
    seed_everything(CFG.RANDOM_SEED)

    device = get_device()

    train_loader, val_loader, class_names = build_dataset()

    model = build_model(len(class_names), device)

    run_step1(model, train_loader, val_loader, device)
    run_step2(model, train_loader, val_loader, device)

    evaluate_model(
        model,
        val_loader,
        class_names,
        device,
        weight_name="best_model.pth"
    )

    print("\nTraining Finished!")
    print(f"Results saved to : {CFG.RESULT_DIR}")

    # Example:
    # predict_image("/content/test.jpg", model, class_names, device)


if __name__ == "__main__":
    main()

